config/routes.rb
Rails.application.routes.draw do
  get 'accounts/show'
  get 'accounts/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#login"

  
  #ユーザー
  resources :users
  resource :account
  resource :session,only:[:create,:destroy] #セッション
  resource :account,only:[:show,:edit,:update]
  
  resources :tasks do
    get "search", on: :collection
  end
  resources :categories 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name,
  presence: true,
  length: {minimum:1, maximum: 20, allow_blank: true}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  #バリデーション
  validates :name,
    presence: true,
    length: {minimum:1, maximum: 20, allow_blank: true},
    uniqueness: {care_sensitive: false}
  validates  :priority,
    presence: true,
    numericality: {
      only_integer:true,
      greater_than: 0,
      less_than: 6,
      allow_blank: true
    }
  validates :done,
    inclusion: { in: [true, false] }  
  validates :category_id,
    presence: true,
    numericality: {
      only_integer:true,
      greater_than: 0,
      allow_blank: true
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name,
  presence: true,
  format: {with: /\A[A-Za-z][A-Za-z0-9]*\z/, allow_blank: true},
  length: {minimum: 2,maximum: 20,allow_blank:true},
  uniqueness: {case_sensitive:false}

  validates :full_name,
  presence: true,
  length: {maximum:20}

  validates :email,
  email: {allow_blank: true}

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :login_required 

  def show
    @user = current_user
  end

  def edit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method:current_user

  private def current_user
    User.find_by(id: session[:user]["id"]) if session[:user]["id"]
  end

  class LoginRequired < StandardError; end
  class Forbidden < StandardError; end

  private def login_required
      raise LoginRequired unless current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :login_required

  def index
    @categories = Category.all
    @username = session[:user]["name"]
  end 

  def show
    @category = Category.find(params[:id])
    @username = session[:user]["name"]
  end
 
  def new
    @category = Category.new
    @username = session[:user]["name"]
  end

  def create
    category_params = params.require(:category).permit(:name)
    @username = session[:user]["name"]
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path,notice:"カテゴリーを作成しました。"
    else
      render "new"
    end
  end


  def edit
    @category = Category.find(params[:id])
    @username = session[:user]["name"]
  end

  def update
    @username = session[:user]["name"]
    category_params = params.require(:category).permit(:name)
    @category = Category.find(params[:id])
    @category.assign_attributes(category_params)
    if @category.save
      redirect_to categories_path,notice:"カテゴリーを更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @username = session[:user]["name"]
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice:"カテゴリーを削除しました。"
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(name: params[:name])
    if user&.authenticate(params[:password])
      session[:user] = user
      redirect_to :categories
    else
      flash.alert = "名前とパスワードが一致しません。"  
      redirect_to :root 
    end
    
  end

  def destroy
    session.delete(:user)
    redirect_to :root
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_categories_list, only: [:new, :create, :edit, :update]
  before_action :login_required

  private def set_categories_list
    @categories_list = []
    @categories = Category.all

    # リストボックスに値を追加
    @categories.each do |category|
      if category.id != 1
        tmp = [category.name,category.id]
        @categories_list << tmp
      end
    end
  end

  #タスク一覧
  def index
    @username = session[:user]["name"]
    if params[:category_id] == nil
      @tasks = Task.all
      @category = Category.new(id:0, name:"すべて")
    else
      @category = Category.find(params[:category_id])
      @tasks = @category.tasks
    end
    
  end

  def show
    @username = session[:user]["name"]
    @task = Task.find(params[:id])
  end

  def new
    @username = session[:user]["name"]
    @task = Task.new
  end



  def create
    @username = session[:user]["name"]
    task_params = params.require(:task).permit(:name,:priority,:date).merge(category_id: params[:category_id],done: false)
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path(category_id: @task.category_id)
    else
      render "new"
    end
  end

  def edit
    @username = session[:user]["name"]
    @task = Task.find(params[:id])
  end

  def update
    @username = session[:user]["name"]
    @task = Task.find(params[:id])
    @task.assign_attributes(params[:task])
    if @task.save
      redirect_to tasks_path(category_id: @task.category_id)
    else
      render "edit"
    end
  end

  def destroy
    @username = session[:user]["name"]
    @task = Task.find(params[:id])
    @category_id = @task.category_id
    @task.destroy
    redirect_to tasks_path(category_id: @category_id), notice:"タスクを削除しました。"
  end

  def checkboxchanged(task_id,is_done)
    @task = Task.find(task_id)
    @task.done = is_done
    if @task.save
      redirect_to tasks_path(category_id: @task.category_id)
    else
      logger.error("タスクのチェックボックスの更新に失敗しました。")
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required

  #ユーザー一覧
  def index
    @users = User.order("id")
  end

  #ユーザー情報の詳細
  def show
    @user = User.find(params[:id])
  end

  #新規作成
  def new
    @user = User.new()
  end

  #編集
  def edit
    @user = User.find(params[:id])
  end

  #ユーザーの新規登録
  def create
    category_params = params.require(:user).permit(:name,:full_name,:email,:birthday,:sex,:administrator,:password)
    @user = User.new(category_params)
    if @user.save
      redirect_to :root ,notice:"ユーザーを登録しました。"
    else
      render "new"
    end
  end

  #ユーザー情報の更新
  def update
    category_params = params.require(:user).permit(:name,:full_name,:email,:birthday,:sex,:administrator,:password)
    @user = User.find(params[:id])
    @user.assign_attributes(category_params)
    if @user.save
      redirect_to @user
    else
      render "edit"
    end
  end

  #ユーザーの削除
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :users
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_item(name, path)
    class_name = 'channel'
    class_name << ' active' if current_page?(path)

    content_tag :li, class:class_name do
      link_to name, path, class: 'channel_name'
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>
<%= render partial: "header" %>  
<% @page_title = "ユーザー情報" %>

<h1><%= @page_title %></h1>

<div><%= link_to "編集",[:edit_account], {class: "btn btn-success"} %></div>

<%= render "users/body"%>

app/views/categories/edit.html.erb
<div class="row">
<div class="col-8" style="background-color:#465568;">
  <%= form_with model: @category, local: true do |f| %>
  <div class=" form-group " >
  <label class="text-light">カテゴリ名</label>
  <%= f.text_field :name, class:"form-control" %>
  </div>
  <%= f.submit "更新", class:"btn btn-primary" %>
  <% end %>
</div>
<div class="col-4 bg-dark" style="padding:0px;">
  <%= render partial:'shared/sidebar', locals:{username: session[:user_id]}%>
</div>

app/views/categories/index.html.erb
<div class="row">
<div class="col-8" style="background-color:#465568;">
  <%# メインコンテナ %>
  <ul class="list-group">
    <li class="list-group-item" id="items">
      <% if @categories.present? %>
        <table class="table table-striped">
          <tbody>
            <tr><%# 「すべて」カテゴリー %>
              <td><%= link_to "すべて", tasks_path %></td>  
              <td></td>
              <td></td>
            </tr>
          <% @categories.each do |category| %> <%# カテゴリーを一覧表示 %>
            <tr>
              <td><%= link_to category.name, tasks_path(category_id: category.id) %></td>  
              <td><%= link_to(content_tag(:i, '' ,class: "far fa-edit"), edit_category_path(id: category.id)) %><%#タスクの削除 %></td>
              <td><%= link_to(content_tag(:i, '' ,class: "far fa-trash-alt"), category_path(id: category.id),data:{ confirm:"本当に削除しますか？"},:method => :delete) %><%#タスクの削除 %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% else %>
      <p>カテゴリーはありません。</p>
      <% end %>
    </li>
  </ul>
  <%= link_to "カテゴリーを追加", new_category_path, class:"btn btn-primary"%>

</div>
<div class="col-4 bg-dark" style="padding:0px;">
    <%= render partial:'shared/sidebar' ,locals:{username:@username}%>
</div>

app/views/categories/new.html.erb
<div class="row">
<div class="col-8" style="background-color:#465568;">
  <%= form_with model: @category, local: true do |f| %>
  <div class=" form-group " >
  <label class="text-light">カテゴリ名</label>
  <%= f.text_field :name, class:"form-control" %>
  </div>
  <%= link_to "戻る", categories_path, class:"btn btn-secondary" %>
  <%= f.submit "作成", class:"btn btn-primary" %>
  <% end %> 
  <%= render partial:"shared/errors", locals:{obj:@category} %>
</div>
<div class="col-4 bg-dark" style="padding:0px; ">
  <%= render'shared/sidebar' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>

  <body>
  <%= render partial: "shared/header" %>  
    <%= yield %>
    <% if flash.notice %>
      <div class="alert alert-secondary"><%= flash.notice %></div>
    <% end %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
  <div id="errors">
    <h3>エラーがあります。</h3>

    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <h1 class="navbar-brand text-light">ToDo</h1>
</nav>  

app/views/shared/_header_login.html.erb
<div class=" ">
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <h1 class="navbar-brand text-light">ToDo</h1>  
  </nav>
</div>

app/views/shared/_login_form.html.erb
<div class="card text-white bg-dark d-inline-block" style="max-width: 20rem;">
  <div class="card-header">ログイン</div>
  <div class="card-body">
    <%= form_tag :session, class:"login-form" do %>
        <div class="form-group">
          <input class="form-control placeholder-no-fix" type="text" name="name" placeholder="ユーザー名" >
          <br>
          <input class="form-control placeholder-no-fix" type="password" name="password" placeholder="パスワード" >
        </div>
          <input type="submit" value="ログイン" class ="btn btn-login ">
      <% end %>
  </div>
</div>
<br> 
<a href=<%= new_user_path %>>新規登録</a>

app/views/shared/_sidebar.html.erb
<div class="listings bg-dark" >
  <div class="listings_channels ">
    <h2 class="listings_header"><%= session[:user]["name"] %></h2>
    <ul class="channel_list">
      <%= sidebar_link_item('ユーザー情報編集', edit_user_path(id: session[:user]["id"])) %>
      <% if current_user.administrator %>
        <%= sidebar_link_item('ユーザー一覧', :users) %>
      <% end %>
        <%= sidebar_link_item('カテゴリー一覧', :categories) %>
        <br>
        <%= sidebar_link_item('ログアウト', :root) %>
      </ul>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="row">
<div class="col-8" style="background-color:#465568;">
  <%= form_with model: @task, url: tasks_path(category_id: params[:category_id]), local:true do |form| %>
    
    <table>
    <tr>
      <th><%= form.label :name,"タスク名", class:"text-white"%></th>
      <td><%= form.text_field :name , class:"form-control"%></td>
    </tr>
    <tr>
      <th><%= form.label :date,"日付", class:"text-white"%></th>
      <td><%= form.date_select :date, start_year:Time.current.year, use_month_numbers:true , class:"form-control"%></td>
    </tr>
    <tr>
      <th><%= form.label :priority,"優先度", class:"text-white"%></th>
      <td>
        <%= form.select :priority,[["1",1],["2",2],["3",3]],{},{class:"form-control"} %>
      </td>
    </tr>
      <tr>
      <th><%= form.label :category_id,"カテゴリー", class:"text-white"%></th>
      <td>
        <%= form.select :category_id,@categories_list,{},{class:"form-control"} %>
      </td>
    </tr>
  </table>
    <%= link_to "戻る", categories_path, class:"btn btn-secondary" %>
    <%= form.submit "追加", class:"btn btn-primary"%>
  <% end %>
<%= render partial:"shared/errors", locals:{obj:@task} %>
</div>
<div class="col-4 bg-dark" style="padding:0px;">
  <%= render'shared/sidebar' %>
</div>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-8 text-center" style="background-color:#465568;">
    <ul class="list-group">
      <%#カテゴリー名 %>
      <li class="list-group-item "><%= @category.name %></li>

      <%#タスク一覧 %>
      <li class="list-group-item" id="items">
        <% if @tasks.present? %>
          <table class="table table-striped">
            <tbody>
            <%#タスクの表示 %>
              <% @tasks.each do |task| %>
              <tr>
                <th><input type="checkbox" name="done" class="done" checked=<%=task.done %>> </th>
                <td><%= task.name %></td>
                <td><%= task.date %></td>
                <td>

                  <%= link_to(content_tag(:i, '' ,class: "far fa-edit"), edit_task_path(id: task.id)) %><%#タスクの編集 %>
                  <%= link_to(content_tag(:i, '' ,class: "far fa-trash-alt"), task_path(id: task.id), :method => :delete,data:{ confirm:"本当に削除しますか？"}) %><%#タスクの削除 %>
                    
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
        <p>タスクはありません。</p>
        <% end %>
      </li>
    </ul>
    <%= link_to "戻る", categories_path, class:"btn btn-secondary" %>
    <%= link_to "タスクを追加", new_task_path(category_id: @category.id), class:"btn btn-primary"%>
  </div>
  <div class="col-4" style="padding:0px;">
    <%= render "shared/sidebar" %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
<div class="col-8" style="background-color:#465568;">
  <%= form_with model: @task, url: tasks_path(category_id: params[:category_id]), local:true do |form| %>
    
    <table>
    <tr>
      <th><%= form.label :name,"タスク名", class:"text-white"%></th>
      <td><%= form.text_field :name , class:"form-control"%></td>
    </tr>
    <tr>
      <th><%= form.label :date,"日付" , class:"text-white"%></th>
      <td><%= form.date_select :date, start_year:Time.current.year, use_month_numbers:true , class:"form-control"%></td>
    </tr>
    <tr>
      <th><%= form.label :priority,"優先度", class:"text-white"%></th>
      <td>
        <%= form.select :priority,[["1",1],["2",2],["3",3]],{},{class:"form-control"} %>
      </td>
    </tr>
      <tr>
      <th><%= form.label :category_id,"カテゴリー", class:"text-white"%></th>
      <td>
        <%= form.select :category_id,@categories_list,{},{class:"form-control"} %>
      </td>
    </tr>
  </table>
    <%= link_to "戻る", categories_path, class:"btn btn-secondary" %>
    <%  %>
    <%= form.submit "追加", class:"btn btn-primary"%>
  <% end %>
<%= render partial:"shared/errors", locals:{obj:@task} %>
</div>
<div class="col-4 bg-dark" style="padding:0px;">
  <%= render'shared/sidebar' %>
</div>

app/views/top/login.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col"></div>
    <div class="col" style="text-align:center">
      <%= render partial:"shared/login_form" %>
      <%if flash.alert %> <p class="alert text-white"><%= flash.alert %></p><% end %>
    </div>
    <div class="col"></div>
  </div>    
</div> 

app/views/users/_body.html.erb
<table class="table table-striped">
  <tr>
    <th>ユーザー名</th>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <th>本名</th>
    <td><%= @user.full_name %></td>
  </tr>  
  <tr>
    <th>性別</th>
    <td><%= @user.sex==1 ? "男":"女" %></td>
  </tr>  
  <tr>
    <th>誕生日</th>
    <td><%= @user.birthday&.strftime("%Y年%m月%d日")%></td>
  </tr>  
  <tr>
    <th>メールアドレス</th>
    <td><%= @user.email %></td>
  </tr>  
  <tr>
    <th>管理者権限</th>
    <td><%= @user.administrator? ? "〇":"-" %></td>
  </tr>
  <tr>
    <th>パスワード</th>
    <td><%= @user.password_digest %></td>
  </tr>
</table>

app/views/users/_userform.html.erb
<%= render partial: "shared/errors", locals: {obj: @user} %>  

<table class="table table-striped">
  <tr>
    <th><%= form.label :name,"ユーザー名" %></th>
    <td><%= form.text_field :name %><td>
  </tr>
  <tr>
    <th><%= form.label :full_name,"本名" %></th>
    <td><%= form.text_field :full_name %><td>
  </tr>
  <tr>
    <th>性別</th>
    <td>
      <%= form.radio_button :sex,1 %>
      <%= form.label :sex_1,"男" %>
      <%= form.radio_button :sex,2 %>
      <%= form.label :sex_2,"女" %>
    </td>
  </tr>
  <tr>  
    <th><%= form.label :birthday,"誕生日" %></th>
    <td>
      <%= form.date_select :birthday,
          start_year:1940,end_year: Time.current.year,
          use_month_numbers: true %>
    </td>
  </tr>
  <tr>
    <th><%= form.label :email,"メールアドレス" %></th>
    <td><%= form.text_field :email %></td>
  </tr>
  <tr>
    <th>管理者</th>
    <td>
      <%= form.check_box :administrator %>
      <%= form.label :administrator, "管理者" %>
    </td>
  </tr>
</table>

app/views/users/edit.html.erb
<% @page_title = "ユーザーの情報編集" %>

<h1><%=@page_title %></h1>


<%= form_with model:@user, local: true do |form| %>

<table class="table table-striped">
  <tr>
    <th><%= form.label :name,"ユーザー名" %></th>
    <td><%= form.text_field :name %><td>
  </tr>
  <tr>
    <th><%= form.label :full_name,"本名" %></th>
    <td><%= form.text_field :full_name %><td>
  </tr>
  <tr>
    <th>性別</th>
    <td>
      <%= form.radio_button :sex,1 %>
      <%= form.label :sex_1,"男" %>
      <%= form.radio_button :sex,2 %>
      <%= form.label :sex_2,"女" %>
    </td>
  </tr>
  <tr>  
    <th><%= form.label :birthday,"誕生日" %></th>
    <td>
      <%= form.date_select :birthday,
          start_year:1940,end_year: Time.current.year,
          use_month_numbers: true %>
    </td>
  </tr>
  <tr>
    <th><%= form.label :email,"メールアドレス" %></th>
    <td><%= form.text_field :email %></td>
  </tr>
  <tr>
    <th><%= form.label :password_digest,"パスワード" %></th>
    <td><%= form.password_field :password_digest %><td>
  </tr>
  <tr>
    <th>管理者</th>
    <td>
      <%= form.check_box :administrator %>
      <%= form.label :administrator, "管理者" %>
    </td>
  </tr>
</table>
  <%= form.submit "更新", class:"btn btn-primary" %>
<% end %>
<%= render partial: "shared/errors", locals: {obj: @user} %>  

app/views/users/index.html.erb
<div class="row">
<div class="col-8">
<% if @users.present? %>
  <table  class="table table-striped">
    <tr>
      <th>ユーザー名</th>
      <th>本名</th>
      <th>操作</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name,user %></td>
      <td><%= user.full_name %></td>
      <td>
        <%= link_to "編集",[:edit, user], {class: "btn btn-success"} %>
        <%= link_to "削除",user, {method: :delete,
            data:{confirm: "本当に削除しますか？"} , class: "btn btn-danger" } %>
      </td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p>会員情報がありません。</p>
<% end %>
<a href="javascript:history.back()" class="btn btn-secondary">戻る</a>
<%= link_to "新規登録", new_user_path,{class: "btn btn-primary"} %>
</div>
<div class="col-4 bg-dark" style="padding:0px;">
  <%= render'shared/sidebar' %>
</div>

app/views/users/new.html.erb
<% @page_title = "ユーザーの新規登録" %>

<h1><%=@page_title %></h1>

<%= form_with model:@user, local: true do |form| %>
  <%= render partial: "shared/errors", locals: {obj: @user} %>  

<table class="table table-striped">
  <tr>
    <th><%= form.label :name,"ユーザー名" %></th>
    <td><%= form.text_field :name %><td>
  </tr>
  <tr>
    <th><%= form.label :full_name,"本名" %></th>
    <td><%= form.text_field :full_name %><td>
  </tr>
  <tr>
    <th>性別</th>
    <td>
      <%= form.radio_button :sex,1 %>
      <%= form.label :sex_1,"男" %>
      <%= form.radio_button :sex,2 %>
      <%= form.label :sex_2,"女" %>
    </td>
  </tr>
  <tr>  
    <th><%= form.label :birthday,"誕生日" %></th>
    <td>
      <%= form.date_select :birthday,
          start_year:1940,end_year: Time.current.year,
          use_month_numbers: true %>
    </td>
  </tr>
  <tr>
    <th><%= form.label :email,"メールアドレス" %></th>
    <td><%= form.text_field :email %></td>
  </tr>
  <tr>
    <th><%= form.label :password,"パスワード" %></th>
    <td><%= form.password_field :password %><td>
  </tr>
  <%
=begin%>
 <tr>
    <th>管理者</th>
    <td>
      <%= form.check_box :administrator %>
      <%= form.label :administrator, "管理者" %>
    </td>
  </tr> 
<%
=end%>
</table>
<a href="javascript:history.back()" class="btn btn-secondary">戻る</a>
<%= form.submit "作成", class:"btn btn-primary" %>

<% end %>

app/views/users/show.html.erb
<% @page_title = "ユーザ情報" %>

<h1><%= @page_title %></h1>

<div><%= link_to "編集",[:edit, @user], {class: "btn btn-success"} %></div>

<%= render "body"%>